### ISSUE TITLE
May I ask which license will you use?

### ISSUE THREAD

**Issue by circlelq** [jtloong/git-status-size#7]
This is a good repository, but still have some problem in my computer. For example, if a file is deleted, `stat` can't find it. I want to change it and publish in GitHub. I want to ask which license will you use?

**Comment by jtloong** [comment]
If you have a bug and a fix in mind, you can feel free to create a pull request in this repo :) It might be better for people if all the fixes are in one place.

In terms of license, you're free to use it however you want. I don't have anything specific for this project though I should add one.

**Comment by circlelq** [comment]
Thanks for your reply.
